apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: disk
                operator: In
                values:
                  - ssd
              - key: topology.kubernetes.io/zone
                operator: In
                value: us-east-1b
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
